# Generated by Django 5.2.3 on 2025-06-28 03:54

import visitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vis_date', models.DateField(blank=True, null=True, verbose_name='Date:')),
                ('vis_time', models.TimeField(blank=True, null=True, verbose_name='Time:')),
                ('vis_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Visitor's Name:")),
                ('vis_address', models.TextField(blank=True, null=True, verbose_name='Address:')),
                ('vis_mobile', models.PositiveBigIntegerField(blank=True, null=True, validators=[visitor.models.validate_mobile], verbose_name='Mobile:')),
                ('vis_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('vis_reason', models.TextField(blank=True, null=True, verbose_name='Purpose of Visit:')),
                ('vis_photo', models.ImageField(blank=True, default='../static/images/No_Image.jpg', null=True, upload_to='visitor', verbose_name='Photograph of Visitor:')),
                ('vis_remarks', models.TextField(blank=True, null=True, verbose_name='Remarks:')),
                ('vis_met', models.BooleanField(default=False, verbose_name='\xa0\xa0Met with DHR (Yes/No):')),
                ('vis_updated', models.DateTimeField(auto_now=True)),
                ('vis_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
