# Generated by Django 5.2.3 on 2025-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
