# Generated by Django 5.2.3 on 2025-07-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_face_encoding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='face_encoding',
            new_name='vis_face_encoding',
        ),
    ]
