# Generated by Django 5.2.3 on 2025-06-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('plan_time', models.TimeField()),
                ('plan_text', models.TextField()),
                ('plan_venue', models.CharField(max_length=60)),
                ('plan_file', models.FileField(blank=True, default='../static/images/BLANK.pdf', null=True, upload_to='planner')),
                ('plan_remarks', models.CharField(max_length=200)),
                ('plan_updated', models.DateTimeField(auto_now=True)),
                ('plan_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
