# Generated by Django 5.2.3 on 2025-06-29 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_planner_options_alter_planner_plan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='planner'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 10, 5, 796667), null=True, verbose_name='Time: '),
        ),
    ]
