# Generated by Django 5.2.3 on 2025-06-30 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_planner_plan_file_alter_planner_plan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='plan_file',
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 30), null=True, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 8, 29, 587198), null=True, verbose_name='Time: '),
        ),
    ]
