# Generated by Django 5.2.3 on 2025-06-30 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_planner_plan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 26, 7, 342564), null=True, verbose_name='Time: '),
        ),
    ]
