# Generated by Django 5.2.3 on 2025-06-30 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_planner_plan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='planner', verbose_name='Related Correspondance (.pdf):'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Time: '),
        ),
    ]
