# Generated by Django 5.2.3 on 2025-06-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vis_date', models.DateField()),
                ('vis_time', models.TimeField()),
                ('vis_name', models.CharField(max_length=200)),
                ('vis_address', models.TextField()),
                ('vis_mobile', models.PositiveIntegerField()),
                ('vis_email', models.EmailField(max_length=254)),
                ('vis_reason', models.TextField()),
                ('vis_met', models.BooleanField()),
                ('vis_photo', models.ImageField(blank=True, default='D:\\dhr_sec\\dhr_sec\\staticfiles/No_Image.jpg', null=True, upload_to='assets')),
                ('vis_remarks', models.TextField()),
            ],
        ),
    ]
