# Generated by Django 5.2.3 on 2025-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_visitor_vis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_met',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vis_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
