# Generated by Django 5.2.3 on 2025-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_alter_visitor_vis_address_alter_visitor_vis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_photo',
            field=models.ImageField(blank=True, default='../static/images/No_Image.jpg', null=True, upload_to='visitor/'),
        ),
    ]
