# Generated by Django 5.2.3 on 2025-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_alter_visitor_vis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_photo',
            field=models.ImageField(default='../static/images/No_Image.jpg', upload_to='visitor/'),
        ),
    ]
