# Generated by Django 5.2.3 on 2025-06-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0009_alter_visitor_vis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor'),
        ),
    ]
