# Generated by Django 5.2.3 on 2025-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0011_alter_visitor_vis_address_alter_visitor_vis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_met',
            field=models.BooleanField(blank=True, null=True, verbose_name='&nbsp; &nbsp;Met with DHR (Yes/No):'),
        ),
    ]
