# Generated by Django 5.2.3 on 2025-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_alter_visitor_vis_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_met',
            field=models.BooleanField(blank=True, null=True, verbose_name='\xa0\xa0Met with DHR (Yes/No):'),
        ),
    ]
