# Generated by Django 5.2.3 on 2025-06-27 18:13

import visitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0014_alter_visitor_vis_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[visitor.models.validate_mobile], verbose_name='Mobile:'),
        ),
    ]
