# Generated by Django 5.2.3 on 2025-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0016_alter_visitor_vis_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_photo',
            field=models.ImageField(blank=True, default='../static/images/No_Image.jpg', null=True, upload_to='visitor', verbose_name='Photograph of Visitor:'),
        ),
    ]
