# Generated by Django 5.2.3 on 2025-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_alter_visitor_vis_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='vis_met',
            field=models.BooleanField(default=False, verbose_name='\xa0\xa0Met with DHR (Yes/No):'),
        ),
    ]
