# Generated by Django 5.2.3 on 2025-06-28 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='plan_file',
        ),
        migrations.AddField(
            model_name='planner',
            name='plan_how',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=60, null=True, verbose_name='How to Join: '),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 28), null=True, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks: '),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_text',
            field=models.TextField(blank=True, null=True, verbose_name='Details of Programme: '),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(17, 35, 38, 923795), null=True, verbose_name='Time: '),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_venue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Venue: '),
        ),
    ]
