# Generated by Django 5.2.3 on 2025-06-29 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_planner_plan_file_planner_plan_how_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planner',
            options={'ordering': ['plan_date', 'plan_time']},
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 29), null=True, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 21, 36, 831668), null=True, verbose_name='Time: '),
        ),
    ]
