# Generated by Django 5.2.3 on 2025-06-29 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_planner_plan_file_alter_planner_plan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='planner', verbose_name='Related Correspondance (.pdf):'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 11, 14, 29876), null=True, verbose_name='Time: '),
        ),
    ]
