# Generated by Django 5.2.3 on 2025-06-30 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_planner_plan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=datetime.time(5, 26, 44, 301770), null=True, verbose_name='Time: '),
        ),
    ]
