# Generated by Django 5.2.3 on 2025-06-30 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_planner_plan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='plan_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='plan_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Time: '),
        ),
    ]
